config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'

  resources :posts, except: :destroy do
    member do 
      post 'vote'
    end
    
    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end
  end
  
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :edit, :show, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  sluggable_column :name

  has_many :posts_categories, class_name: "PostCategory"
  has_many :posts, through: :posts_categories

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :user, foreign_key: :user_id
  belongs_to :post, foreign_key: :post_id

  validates :body, presence: true 
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable
  sluggable_column :title

  belongs_to :user, foreign_key: :user_id
  has_many :comments, foreign_key: :post_id
  has_many :posts_categories, class_name: "PostCategory"
  has_many :categories, through: :posts_categories

  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true

  def belongs_to_user(user_id)
    self.user_id == user_id
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  self.table_name = "posts_categories"
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  sluggable_column :username

  has_many :posts, foreign_key: :user_id
  has_many :comments, foreign_key: :user_id
  has_many :votes

  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :password, presence: true, length: { minimum: 5 }, on: :create
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user_id, scope: [:voteable_type, :voteable_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= session[:user_id] ? User.find(session[:user_id]) : nil
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to :back
    end
  end

  def total_votes
    resource.votes
  end

  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :set_category, only: [:show]
  before_action :require_user, only: [:new, :create]

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category successfully created"
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def show
  end

  def new
    @category = Category.new
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find_by(slug: params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:notice] = "Comment was successfully created"
      redirect_to post_path(@post)
    else
      # Deletion is necessary, otherwise the comments partial tries to
      # render the in-memory comment and throws an error
      @post.comments.delete(@comment)
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    vote = Vote.new(vote: params[:vote], user_id: current_user.id, voteable: @comment)
    if vote.save
      flash.now[:notice] = "Your vote on the comment has been counted."
    else
      flash.now[:error] = "You can't vote on a comment more than once."
    end
    @resource = @comment
    respond_to do |format|
      format.js { render 'posts/vote' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  helper_method :belongs_to_user

  def index
    @posts = Post.all.sort_by { |post| post.total_votes }.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    if @post.belongs_to_user(session[:user_id])
      render :edit
    else 
      flash[:alert] = "You must be the creator of "\
                      "the post to do that."
      redirect_to root_path
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    vote = Vote.new(vote: params[:vote], user_id: current_user.id, voteable: @post)
    if vote.save
      flash.now[:notice] = "Your vote on #{@post.title} has been counted."
    else
      flash.now[:error] = "You can't vote on #{@post.title} more than once."
    end

    @resource = @post
    respond_to do |format|
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      flash[:notice] = "You are already logged in."
      redirect_to root_path
    else
      render :login
    end
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have been logged in."
      redirect_to root_path
    else
      flash[:alert] = "There was a problem with your username or password."
      render :login
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, except: [:new, :create]
  before_action :require_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
     
    if @user.save
      flash[:notice] = "You have been registered."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile has been updated."
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :timezone)
  end
  
  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def require_same_user
    if @user != current_user
      flash[:error] = "You're not allowed to do that."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    if (str.starts_with?('http://') || str.starts_with?('https://'))
      str
    else
      'http://' + str
    end
  end

  def fix_time(dt)
    if logged_in? && !current_user.timezone.blank?
      dt = dt.in_time_zone(current_user.timezone)
    end
    
    dt.strftime("%m/%d/%Y %I:%M%p %Z")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category)%></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>
<%= render 'shared/errors', resource: @category %>

<div class="well">
  <%= form_for @category do |f| %>
  <div class="control-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit "Create Category", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% all_posts = link_to 'All Posts', posts_path %>
<%= render 'shared/content_title', title: "#{all_posts} &raquo #{@category.name}".html_safe %>
<%= render 'posts/posts', posts: @category.posts %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span>
  <% end %>
  <ul class='dropdown-menu'>
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
    <% if logged_in? %>
      <li class="divider"></li>
      <li>
        <%= link_to(new_category_path) do %>
          <i class="icon-plus"></i>
          New Category
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<div class="nav_item">
  <% if logged_in? %>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  <% else %>
    <%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %>
  <% end %>
</div>
<% if logged_in? %>
  <div class="btn-group nav_item">
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      <%= current_user.username %> <span class='caret'></span>
    <% end %>
    <ul class="dropdown-menu">
      <li>
        <%= link_to edit_user_path(current_user) do %>
          <i class="icon-pencil"></i>
          edit profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user) do %>
          <i class="icon-user"></i>
          view profile
          <% end %>
      </li>
      <li>
        <%= link_to logout_path do %>
        <i class="icon-circle-arrow-left"></i>
        log out
        <% end %>
      </li>
    </ul>
  </div>
<% else %>
  <div class="nav_item">
    <%= link_to 'Log in', login_path, class: 'btn btn-small' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <div id="messages"><%= render 'layouts/messages' %></div>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_comments.html.erb
<h5>Comments:</h5>
<% comments.each do |comment| %>
<div class="row" >
  <%= render 'posts/vote', resources: [comment.post, comment], path: method(:vote_post_comment_path), vote_count: comment.total_votes %>
  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if profile_comments %>
      on <%= link_to "#{comment.post.title}", post_path(comment.post) %>
    <% end %>
    <br/>
    by <%= link_to comment.user.username, '' %> 
    at <%= fix_time(comment.created_at) %>
  </div>
</div>
<br/>
<% end %>

app/views/posts/_form.html.erb
<%= render 'shared/errors', resource: @post %>

<%= form_for @post do |f| %>
  <div class="control-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="control-group">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="control-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>
  </div>
  <div class="control-group">
  <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>
  <%= f.submit "#{button_value}", class: 'btn btn-primary' %>
<% end %>

app/views/posts/_posts.html.erb
<% posts.each do |post|%>
  <%= render 'posts/vote', resources: [post], path: method(:vote_post_path), vote_count: post.total_votes %>
  <div class="row">
    <div class='span8 well'>
      <%= render post.categories %>
      <h4><%= link_to post.title, fix_url(post.url) %></h4>
      <p><%= post.description %></p>
      <p>
        <span class="quiet">posted by <%= post.user.username %></span>
        <small>at <%= fix_time(post.created_at) %></small>
      </p>
      <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
      </small>
    </div>
  </div>
<% end %>

app/views/posts/_vote.html.erb
<div class="span0 well text-center">
  <% if logged_in? %>
    <%= link_to path.call(*resources, vote: true), method: 'post', remote: true do %>
      <i class="icon-arrow-up"></i>
    <% end %>
    <br/>
  <% end %>
    <span id="<%= resources[-1].class.name + resources[-1].id.to_s %>"><%= "#{vote_count} #{vote_count.abs == 1 ? 'vote' : 'votes'}" %></span>
  <% if logged_in? %>
    <br/>
    <%= link_to path.call(*resources, vote: false), method: 'post', remote: true do %>
      <i class="icon-arrow-down"></i>
    <% end %>
  <% end %>
  </div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit Post" %>
<%= render 'form', button_value: "Edit Post" %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<%= render 'posts', posts: @posts %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create A New Post" %>
<%= render 'form', button_value: "Create Post" %>

app/views/posts/show.html.erb
<% if @post.belongs_to_user(session[:user_id]) %>
  <p class='pull-right'>
    <%= link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-primary' %>
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', resource: @comment %>
    <%= f.label :body, "Leave a comment" %>
    <%= f.text_area :body, rows: 3, class: 'span4' %>
    <br/>
    <%= f.submit "Create comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<%= render 'posts/comments', profile_comments: false, comments: @post.comments %>

app/views/posts/vote.js.erb
function voteCountText(count) {
  return `${count} ` + `${Math.abs(count) === 1 ? "vote" : "votes"}`;
}

let newVoteCountText = voteCountText(<%= @resource.total_votes %>);
$("#<%= @resource.class.name + @resource.id.to_s %>").text(newVoteCountText);
$("#messages").html("<%= j render partial: 'layouts/messages' %>");

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div class='alert alert-error' >
  <h5>Please fix the following errors:</h5>
  <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/users/_user_form.html.erb
<%= form_for user do |f| %>
  <div class="well">
    <div class="control-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="control-group">
      <%= f.label :timezone %>
      <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones %>
    </div>
    <div class="control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit "#{button_value}", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Update Profile" %>
<%= render 'shared/errors', resource: @user %>
<%= render 'user_form', user: @user, button_value: "Update" %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: "Register" %>
<%= render 'shared/errors', resource: @user %>
<%= render 'user_form', user: @user, button_value: "Register" %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>
<div class="well">
  <dl class="dl-horizontal">
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
  </dl>
  <dl class="dl-horizontal">
    <dt>Time Zone:</dt>
    <dd><%= @user.timezone %></dd>
  </dl>
</div>
<h5><%= @user.username %>'s Activity</h5>
<ul class='nav nav-tabs'>
  <li class=<%= params[:tab] ? '' : 'active' %>>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class=<%= params[:tab] ? "active" : '' %>>
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: "comments") %>
  </li>
</ul>
<% if params[:tab] %>
  <%= render 'posts/comments', profile_comments: true, comments: @user.comments %>
<% else %>
  <%= render 'posts/posts', posts: @user.posts %>
<% end %>